name: Release Docker

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    name: Release Docker
    steps:
      - name: Set version
        run: |
          ref=${GITHUB_REF#refs/*/}
          if [ $ref = "master" ]; then
            version="latest"
          else
            version=$ref
          fi
          echo "REF=${ref}" >> $GITHUB_ENV
          echo "VERSION=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: treydock
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: treydock
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            treydock/cgroup_exporter:${{ env.VERSION }}
            quay.io/treydock/cgroup_exporter:${{ env.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
